export const creepInfo0 = {
    harvester: {num: 2, 
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, 
                        WORK, WORK, WORK, WORK, WORK, WORK, WORK,
                        WORK, WORK, WORK, WORK, WORK, WORK, WORK,
                    ]},
    mine_harvester: {num: 0, 
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        WORK, WORK, WORK, WORK, WORK, WORK,
                    ]},
    upgrader: {num: 1, 
                parts: [MOVE,  
                        CARRY, 
                        WORK,  ],
                // parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                //         CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY,
                //         WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, 
                // ]
                },
    builder: {num: 1, 
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, 
                        CARRY, CARRY, CARRY, CARRY, 
                        WORK, WORK, WORK, WORK, 
                    ]},
    carrier: {num: 1, 
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, 
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                    ]},
    repairer: {num: 0, 
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        WORK, WORK, WORK, WORK, WORK, WORK,
                ]},
    defender: {num: 1,
                parts: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH,
                        MOVE, MOVE, MOVE, MOVE, MOVE, 
                        ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                        ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                        ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                        ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                    ]},
    transferer: {num: 1,
                parts: [MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY,
                ]},
    mover: {num: 1, 
            parts: [MOVE,
                    CARRY,
                    ]},
    traveller: {num: 0,
                parts: [
                        MOVE,MOVE,CARRY,WORK,MOVE,MOVE,CARRY,WORK,MOVE,MOVE,CARRY,WORK,
                        MOVE,MOVE,CARRY,WORK,MOVE,MOVE,CARRY,WORK,MOVE,MOVE,CARRY,WORK,
                        MOVE,MOVE,WORK,WORK,MOVE,MOVE,CARRY,WORK,MOVE,MOVE,WORK,WORK,
                        MOVE,MOVE,WORK,WORK,MOVE,MOVE,WORK,WORK,MOVE,MOVE,WORK,WORK,
                        MOVE, WORK,
                        ]},
    claimer: {
            E8S47: {num: 0, 
                parts: [MOVE,MOVE,CLAIM,CLAIM
                ]},
            E7S49: {num: 1, 
                parts: [MOVE,MOVE,CLAIM,CLAIM
                ]},
            E8S48: {num: 1, 
                parts: [MOVE,MOVE,CLAIM,CLAIM
                ]},
            E9S47: {num: 0, 
                parts: [MOVE,MOVE,CLAIM,CLAIM
                ]},
            E7S47: {num: 1, 
                parts: [MOVE,MOVE,CLAIM,CLAIM
                ]},
            E8S49: {num: 1, 
                parts: [MOVE,MOVE,CLAIM,CLAIM
                ]},
        },
    remoteHarvester: {
            E8S47: {num: 0, 
                parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                    CARRY,
                    WORK,WORK,WORK,WORK,WORK
            ]},
            E7S49: {num: 1, 
                parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                    CARRY,
                    WORK,WORK,WORK,WORK,WORK
            ]},
            E8S48: {num: 1, 
                parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                    CARRY,
                    WORK,WORK,WORK,WORK,WORK
            ]},
            E9S47: {num: 0, 
                parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                    CARRY,
                    WORK,WORK,WORK,WORK,WORK
            ]},
            E7S47: {num: 1, 
                parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                    CARRY,
                    WORK,WORK,WORK,WORK,WORK
            ]},
            E8S49: {num: 1, 
                parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                    CARRY,
                    WORK,WORK,WORK,WORK,WORK
            ]},
    },
    remoteCarrier: {
        E8S47: {num: 0,
                backTo: 'E8S47',
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE,RANGED_ATTACK,RANGED_ATTACK,ATTACK,ATTACK,ATTACK
                    ]},
            E7S49: {num: 1, 
                backTo: 'E7S48',
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE,RANGED_ATTACK,RANGED_ATTACK,ATTACK,ATTACK,ATTACK
                    ]},
            E8S48: {num: 1, 
                backTo: 'E8S47',
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE,RANGED_ATTACK,RANGED_ATTACK,ATTACK,ATTACK,ATTACK
                    ]},
            E9S47: {num: 0, 
                backTo: 'E7S48',
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE,RANGED_ATTACK,RANGED_ATTACK,ATTACK,ATTACK,ATTACK
                    ]},
            E7S47: {num: 1, 
                backTo: 'E7S48',
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE,RANGED_ATTACK,RANGED_ATTACK,ATTACK,ATTACK,ATTACK
                        ]},
            E8S49: {num: 1, 
                backTo:'E8S47',
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                        MOVE, MOVE, MOVE, MOVE, MOVE,RANGED_ATTACK,RANGED_ATTACK,ATTACK,ATTACK,ATTACK
                        ]},
        },

}

export const creepInfo1 = {
        harvester: {num: 0, 
                    parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                            CARRY, 
                            WORK, WORK, WORK, WORK, WORK, WORK, WORK,
                            WORK, WORK, WORK, WORK, WORK, WORK, WORK,
                        ]},
        mine_harvester: {num: 0, 
                    parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                            CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                            WORK, WORK, WORK, WORK, WORK, WORK,
                        ]},
        upgrader: {num: 2, 
                    parts: [MOVE, MOVE, MOVE, MOVE, MOVE,MOVE, MOVE,MOVE,MOVE,MOVE,
                            CARRY, CARRY,CARRY, CARRY,CARRY,
                            WORK, WORK, WORK,WORK,WORK,
                        ],
                    // parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                    //         CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY,
                    //         WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, 
                    // ]
                    },
        builder: {num: 2, 
                    parts: [MOVE, MOVE, MOVE, MOVE, MOVE,MOVE, MOVE,MOVE,MOVE,MOVE,
                            CARRY, CARRY,CARRY, CARRY,CARRY,
                            WORK, WORK, WORK,WORK,WORK,
                        ]},
        carrier: {num: 1, 
                    parts: [MOVE, MOVE, MOVE,MOVE ,MOVE,MOVE ,
                            CARRY, CARRY, CARRY,CARRY,  CARRY,CARRY,
                        ]},
        repairer: {num: 0, 
                    parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
                            CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                            WORK, WORK, WORK, WORK, WORK, WORK,
                    ]},
        defender: {num: 0,
                    parts: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH,
                            MOVE, MOVE, MOVE, MOVE, MOVE, 
                            ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                            ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                            ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                            ATTACK, MOVE, ATTACK, MOVE, ATTACK, MOVE, 
                        ]},
        transferer: {num: 0,
                    parts: [MOVE,
                            CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY,
                            CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,CARRY, CARRY,
                    ]},
        mover: {num: 0, 
                parts: [MOVE,
                        CARRY,
                        ]},
        remoteCarrier: {
        E8S47: {num: 1,
                backTo: 'E8S47',
                parts: [MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,MOVE, 
                        CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY,
                    ]},
        },
        remoteHarvester: {
                E8S47: {num: 2, 
                    parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                        CARRY,
                        WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,
                ]},
                E7S49: {num: 0, 
                    parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                        CARRY,
                        WORK,WORK,WORK,WORK,WORK
                ]},
                E8S48: {num: 0, 
                    parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                        CARRY,
                        WORK,WORK,WORK,WORK,WORK
                ]},
                E9S47: {num: 0, 
                    parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                        CARRY,
                        WORK,WORK,WORK,WORK,WORK
                ]},
                E7S47: {num: 0, 
                    parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                        CARRY,
                        WORK,WORK,WORK,WORK,WORK
                ]},
                E8S49: {num: 0, 
                    parts: [MOVE,MOVE,MOVE,MOVE,MOVE,
                        CARRY,
                        WORK,WORK,WORK,WORK,WORK
                ]},
        },
    
}

export const minimumStorage = 500000;

export const minimumTerminal = 150000;